//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoralAARB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationNo { get; set; }
        public string BranchId { get; set; }
        public string DepartmentId { get; set; }
        public string Tin { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid MainServiceId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string StatusId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual CustomerProfile CustomerProfile { get; set; }
        public virtual Department Department { get; set; }
        public virtual MainService MainService { get; set; }
        public virtual Status Status { get; set; }
    }
}
