//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoralAARB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequirement
    {
        public System.Guid ServiceRequirementId { get; set; }
        public string ServiceRequirementName { get; set; }
        public System.Guid MainServiceId { get; set; }
    
        public virtual MainService MainService { get; set; }
    }
}
